version: "3.8"

services:
  # Flask Application
  flask-app:
    build: ./app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=testdb
    depends_on:
      - mysql
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app
    networks:
      - app-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

# Networks & Volumes
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
